<?php
/**
 * This file is part of the Burdette package.
 *
 * @copyright © Samantha Quiñones & Patryk Kruk, All Rights Reserved
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace Burdette;

/**
 * Interface TokenInterface
 *
 * Tokens objects are generated by strategies and contain information about the state of a given bucket. Tokens may be
 * either allow tokens or disallow tokens. This value is obtained by calling TokenInterface::isAllowed().
 *
 * Tokens also report the identity for which they were generated, the number of available tokens for the identity,
 * and (if set by the strategy), the next time when tokens will be replenished.
 *
 * @author Samantha Quiñones <samantha@tembies.com>
 * @package Burdette
 */
interface TokenInterface
{
    /**
     * @return integer
     */
    public function getAvailable();

    /**
     * @return IdentityInterface
     */
    public function getIdentity();

    /**
     * @return int
     */
    public function getNextReplenish();

    /**
     * @return bool
     */
    public function isAllowed();
}
